import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import type { Metadata } from "next";
import "@ant-design/v5-patch-for-react-19";
import { unstable_ViewTransition as ViewTransition } from "react";
import { App } from "antd";
import { AuthProvider } from "@/components/AuthProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <App>
            <AuthProvider>
              <ViewTransition>{children}</ViewTransition>
            </AuthProvider>
          </App>
        </AntdRegistry>
      </body>
    </html>
  );
}
